export const progModels = [
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Création d'affiche publicitaire",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite la création d'une affiche publicitaire pour promouvoir mon entreprise auprès d'un large public. Les conditions sont d'être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 5000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de logo professionnel",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "J'ai besoin de la conception d'un logo professionnel pour mon entreprise. Les critères incluent la créativité, le professionnalisme et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 8000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Campagne marketing sur les réseaux sociaux",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je recherche une agence pour lancer une campagne marketing efficace sur les réseaux sociaux. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 7200,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de site web responsive",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite la conception d'un site web responsive pour mon entreprise. Les critères incluent la convivialité, la créativité et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 9000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de matériel promotionnel",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "J'ai besoin de la conception de matériel promotionnel (flyers, brochures, etc.) pour une campagne publicitaire. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 5500,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Rédaction de contenu publicitaire",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Recherche service de rédaction de contenu publicitaire percutant pour promouvoir mes produits. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 6000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Développement d'application mobile",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite le développement d'une application mobile pour mon entreprise. Les critères incluent la fonctionnalité, l'innovation et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 10000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Création d'affiche publicitaire",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite la création d'une affiche publicitaire pour promouvoir mon entreprise auprès d'un large public. Les conditions sont d'être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 5000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de logo professionnel",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "J'ai besoin de la conception d'un logo professionnel pour mon entreprise. Les critères incluent la créativité, le professionnalisme et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 8000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Campagne marketing sur les réseaux sociaux",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je recherche une agence pour lancer une campagne marketing efficace sur les réseaux sociaux. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 7200,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de site web responsive",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite la conception d'un site web responsive pour mon entreprise. Les critères incluent la convivialité, la créativité et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 9000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de matériel promotionnel",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "J'ai besoin de la conception de matériel promotionnel (flyers, brochures, etc.) pour une campagne publicitaire. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 5500,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Rédaction de contenu publicitaire",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Recherche service de rédaction de contenu publicitaire percutant pour promouvoir mes produits. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 6000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Développement d'application mobile",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite le développement d'une application mobile pour mon entreprise. Les critères incluent la fonctionnalité, l'innovation et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 10000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Création d'affiche publicitaire",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite la création d'une affiche publicitaire pour promouvoir mon entreprise auprès d'un large public. Les conditions sont d'être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 5000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de logo professionnel",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "J'ai besoin de la conception d'un logo professionnel pour mon entreprise. Les critères incluent la créativité, le professionnalisme et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 8000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Campagne marketing sur les réseaux sociaux",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je recherche une agence pour lancer une campagne marketing efficace sur les réseaux sociaux. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 7200,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de site web responsive",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite la conception d'un site web responsive pour mon entreprise. Les critères incluent la convivialité, la créativité et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 9000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de matériel promotionnel",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "J'ai besoin de la conception de matériel promotionnel (flyers, brochures, etc.) pour une campagne publicitaire. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 5500,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Rédaction de contenu publicitaire",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Recherche service de rédaction de contenu publicitaire percutant pour promouvoir mes produits. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 6000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Développement d'application mobile",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite le développement d'une application mobile pour mon entreprise. Les critères incluent la fonctionnalité, l'innovation et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 10000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Création d'affiche publicitaire",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite la création d'une affiche publicitaire pour promouvoir mon entreprise auprès d'un large public. Les conditions sont d'être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 5000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de logo professionnel",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "J'ai besoin de la conception d'un logo professionnel pour mon entreprise. Les critères incluent la créativité, le professionnalisme et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 8000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Campagne marketing sur les réseaux sociaux",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je recherche une agence pour lancer une campagne marketing efficace sur les réseaux sociaux. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 7200,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de site web responsive",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite la conception d'un site web responsive pour mon entreprise. Les critères incluent la convivialité, la créativité et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 9000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Conception de matériel promotionnel",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "J'ai besoin de la conception de matériel promotionnel (flyers, brochures, etc.) pour une campagne publicitaire. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 5500,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Rédaction de contenu publicitaire",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Recherche service de rédaction de contenu publicitaire percutant pour promouvoir mes produits. Doit être professionnel, créatif et respecter les délais.",
        targetFields: ["11", "5", "1"],
        amount: 6000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
    {
        contractor: [],
        buyer: {
            $oid: "6567c413c902456aa495add3",
        },
        title: "Développement d'application mobile",
        buyerDeadline: 1704240000000,
        finalDeadLine: 0,
        canSubmit: true,
        description:
            "Je souhaite le développement d'une application mobile pour mon entreprise. Les critères incluent la fonctionnalité, l'innovation et le respect des délais.",
        targetFields: ["11", "5", "1"],
        amount: 10000,
        resourcesListe: [],
        isApproved: false,
        projectStatus: 0,
        submitters: [],
        buyerType: 2,
    },
];
