export const apiResponseLang: any = {
    fr: {
        EO: "autre erreur",
        ER: "échec de l'inscription, réessayez plus tard",
        ET: "jeton invalide",
        EN: "erreur de communication réseau avec le CDN",
        E01: "email déjà existant",
        E02: "téléphone déjà existant",
        E03: "aucun compte trouvé",
        E04: "erreur lors de l'édition des détails du compte, réessayez plus tard",
        E05: "mot de passe incorrect pour ce compte",
        E06: "vous devez confirmer votre email avant de vous connecter",
        E07: "aucun jeton fourni",
        S01: "inscription en freelance réussie",
        S02: "connexion en freelance réussie",
        S03: "inscription client réussie",
        S04: "connexion client réussie",
        S05: "authentification réussie",
        E11: "mauvais lien de confirmation par email",
        E12: "erreur lors de la vérification de votre code (mauvais timing)",
        E13: "lien de confirmation par email expiré, réessayez avec un autre lien",
        E14: "chaîne de confirmation obligatoire pour cette route",
        E15: "lien déjà utilisé, essayez avec un autre lien valide",
        E16: "erreur lors de l'envoi de l'email",
        E17: "email déjà confirmé",
        S11: "email vérifié avec succès",
        S12: "email envoyé avec succès",
        S13: "mot de passe changé avec succès",
        E21: "erreur lors de la modification du compte, réessayez plus tard",
        E22: "erreur lors de la suppression du compte, réessayez plus tard",
        S21: "détails du compte modifiés avec succès",
        S22: "compte supprimé avec succès",
        E31: "erreur lors du téléversement de la ressource sur le serveur, réessayez plus tard",
        E32: "erreur lors de la création de votre ressource, réessayez plus tard",
        E33: "aucune ressource trouvée avec cet identifiant",
        E34: "erreur lors de l'enregistrement des modifications, réessayez plus tard",
        E35: "vous ne pouvez pas supprimer une ressource téléchargée plus d'une fois",
        E36: "erreur lors de la suppression de la ressource, réessayez plus tard",
        E37: "la ressource demandée n'est pas publique",
        S31: "ressource téléversée avec succès",
        S32: "ressource modifiée avec succès",
        S33: "ressource supprimée avec succès",
        S34: "ressource(s) trouvée(s) avec succès",
        E41: "non autorisé à ajouter un plan",
        E42: "erreur lors de la création du plan, réessayez plus tard",
        E43: "aucun plan trouvé",
        E44: "erreur lors de l'enregistrement des modifications du plan, réessayez plus tard",
        E45: "erreur lors de la suppression du plan, réessayez plus tard",
        S41: "plan ajouté avec succès",
        S42: "plan modifié avec succès",
        S43: "plan supprimé avec succès",
        S44: "plan(s) trouvé(s) avec succès",
        E101: "erreur lors de l'enregistrement de l'image, réessayez plus tard",
        E102: "erreur lors du traitement de l'image",
        E103: "propriétaire de la ressource obligatoire",
        E104: "la ressource demandée n'existe pas",
        S101: "image enregistrée avec succès",
        S102: "ressources supprimées avec succès",
        formMissing: "un ou plusieurs champs obligatoires sont vides",
        resErr: "erreur lors de la réception de la réponse, veuillez réessayer plus tard",
    },
    ar: {
        EO: "خطأ آخر",
        ER: "فشل في التسجيل، يرجى المحاولة مرة أخرى لاحقًا",
        ET: "رمز مميز غير صالح",
        EN: "خطأ في التواصل مع شبكة CDN",
        E01: "البريد الإلكتروني موجود بالفعل",
        E02: "الهاتف موجود بالفعل",
        E03: "لا يوجد حساب موجود",
        E04: "خطأ في تحرير تفاصيل الحساب، يرجى المحاولة مرة أخرى لاحقًا",
        E05: "كلمة مرور خاطئة لهذا الحساب",
        E06: "يجب عليك تأكيد بريدك الإلكتروني قبل تسجيل الدخول",
        E07: "لم يتم توفير رمز مميز",
        S01: "تم تسجيل العمل الحر بنجاح",
        S02: "تسجيل الدخول للعمل الحر بنجاح",
        S03: "تم تسجيل العميل بنجاح",
        S04: "تسجيل الدخول للعميل بنجاح",
        S05: "المصادقة بنجاح",
        E11: "رابط تأكيد البريد الإلكتروني خاطئ",
        E12: "خطأ أثناء التحقق من الرمز الخاص بك (سوء التوقيت)",
        E13: "انتهت صلاحية رابط تأكيد البريد الإلكتروني، يرجى المحاولة مع رابط آخر",
        E14: "سلسلة التأكيد إلزامية لهذا المسار",
        E15: "الرابط مستخدم بالفعل، جرب استخدام رابط صالح آخر",
        E16: "خطأ أثناء إرسال البريد الإلكتروني",
        E17: "البريد الإلكتروني مؤكد بالفعل",
        S11: "تم التحقق من البريد الإلكتروني بنجاح",
        S12: "تم إرسال البريد الإلكتروني بنجاح",
        S13: "تم تغيير كلمة المرور بنجاح",
        E21: "خطأ أثناء تحرير الحساب، يرجى المحاولة مرة أخرى لاحقًا",
        E22: "خطأ أثناء حذف الحساب، يرجى المحاولة مرة أخرى لاحقًا",
        S21: "تم تحرير تفاصيل الحساب بنجاح",
        S22: "تم حذف الحساب بنجاح",
        E31: "خطأ أثناء تحميل المورد إلى الخادم، يرجى المحاولة مرة أخرى لاحقًا",
        E32: "خطأ أثناء إنشاء المورد الخاص بك، يرجى المحاولة مرة أخرى لاحقًا",
        E33: "لا يوجد مورد موجود بهذا الرقم التعريفي",
        E34: "خطأ أثناء حفظ التغييرات، يرجى المحاولة مرة أخرى لاحقًا",
        E35: "لا يمكنك حذف مورد تم تحميله أكثر من مرة",
        E36: "خطأ أثناء حذف المورد، يرجى المحاولة مرة أخرى لاحقًا",
        E37: "المورد الذي طلبته غير عام",
        S31: "تم تحميل المورد بنجاح",
        S32: "تم تعديل المورد بنجاح",
        S33: "تم حذف المورد بنجاح",
        S34: "تم العثور على المورد (أو الموارد)",
    },
    en: {
        EO: "other error",
        ER: "failed to register try again later",
        ET: "invalid token",
        EN: "network communication with CDN error",
        E01: "email already exist",
        E02: "phone already exist",
        E03: "no account found",
        E04: "account detail edition error try again later",
        E05: "wrong password for this account",
        E06: "you must confirm your email before logging in",
        E07: "no token provided",
        S01: "freelance registered successfully",
        S02: "freelance login successful",
        S03: "client registered successfully",
        S04: "client login successful",
        S05: "authentication successful",
        E11: "wrong email confirmation link",
        E12: "error while verifying your code (wrong timing)",
        E13: "email confirmation link expired try again with another link",
        E14: "confirmation string mandatory for this route",
        E15: "link already used try using another valid link",
        E16: "error while sending the email",
        E17: "email already confirmed",
        S11: "email verified successfully",
        S12: "email sent successfully",
        S13: "password changed successfully",
        E21: "error while editing account try again later",
        E22: "error while deleting account try again later",
        S21: "account details edited successfully",
        S22: "account deleted successfully",
        E31: "error while uploading resource to server try again later",
        E32: "error while creating your resource try again later",
        E33: "no resource found with this id",
        E34: "error while saving changes try again later",
        E35: "you can’t delete a resource downloaded more that 1 time",
        E36: "error while deleting the resource try again later",
        E37: "the resource you requested is not public",
        S31: "resource uploaded successfully",
        S32: "resource edited successfully",
        S33: "resource deleted successfully",
        S34: "resource (s) found successfully",
        E41: "not authorized to add a plan",
        E42: "error while creating plan try again later",
        E43: "no plan found",
        E44: "error while saving plan changes try again later",
        E45: "error while deleting plan try again later",
        S41: "plan added successfully",
        S42: "plan edited successfully",
        S43: "plan deleted successfully",
        S44: "plan (s) found successfully",
        E101: "error while saving image try again later",
        E102: "error while processing image",
        E103: "resource owner mandatory",
        E104: "requested resource doesn’t exist",
        S101: "image saved successfully",
        S102: "resources deleted successfully",
        formMissing: "one or more mandatory field(s) is empty",
        resErr: "error while receiving response, please try again later",
    },
};
