import { langType } from "../../MiddleWear/ClientInterface";

type finLangType = {
    [key in langType]: {
        quotsButt: string;
        invoiceButt: string;
        invoiceResourcesButt: string;
        invoiceSubButt: string;
        balanceButt: string;
        noInvoices: string;
        noQuots: string;
        invoice: string;
        quot: string;
        card: {
            emmiter: string;
            targer: string;
            totalAmount: string;
            created: string;
            edited: string;
            isPayer: string;
            isNotPayed: string;
            invFor: string;
            detailButt: string;
            type: {
                [key in any]: string;
            };
        };
        detail: {
            invoiceNum: string;
            designation: string;
            qte: string;
            price: string;
            discount: string;
            totalPrice: string;
            grossTotal: string;
            generatedFooter: string;
        };
    };
};

export const FinManagementLang: finLangType = {
    fr: {
        quotsButt: "mes devis",
        invoiceButt: "mes factures",
        invoiceResourcesButt: "factures d'achats",
        invoiceSubButt: "factures d'abonnement",
        balanceButt: "portefeuille",
        noInvoices: "pas de factures pour l'instant",
        noQuots: "pas de devis pour l'instant",
        invoice: "facture",
        quot: "devis",
        card: {
            emmiter: "émetteur",
            targer: "facturé a",
            totalAmount: "montant TTC",
            created: "créé le",
            edited: "édité le",
            isPayer: "payée",
            isNotPayed: "non payée",
            invFor: "facture pour",
            detailButt: "détails de la facture",
            type: {
                "1": "achat resource",
                "2": "projet",
                "3": "abonnement",
            },
        },
        detail: {
            invoiceNum: "N°",
            designation: "désignation",
            price: "prix",
            discount: "réduction (%)",
            totalPrice: "total",
            qte: "quantité",
            grossTotal: "total HT",
            generatedFooter: "facture génerée automatiquement par la plateforme Sahla & Mahla ™",
        },
    },
    en: {
        quotsButt: "my quotes",
        invoiceButt: "my invoices",
        invoiceResourcesButt: "purchase invoices",
        invoiceSubButt: "subscription invoices",
        balanceButt: "wallet",
        noInvoices: "no invoices at the moment",
        noQuots: "no quotes at the moment",
        invoice: "invoice",
        quot: "quote",
        card: {
            emmiter: "emitter",
            targer: "charged to",
            totalAmount: "total amount",
            created: "created on",
            edited: "edited on",
            isPayer: "paid",
            isNotPayed: "unpaid",
            invFor: "invoice for",
            detailButt: "invoice details",
            type: {
                "1": "resource purchase",
                "2": "project",
                "3": "subscription",
            },
        },
        detail: {
            invoiceNum: "No.",
            designation: "designation",
            price: "price",
            discount: "discount (%)",
            totalPrice: "total",
            qte: "quantity",
            grossTotal: "total before tax",
            generatedFooter: "invoice automatically generated by Sahla & Mahla ™ platform",
        },
    },
    ar: {
        quotsButt: "عروضي",
        invoiceButt: "فواتيري",
        invoiceResourcesButt: "فواتير الشراء",
        invoiceSubButt: "فواتير الاشتراكات",
        balanceButt: "محفظتي",
        noInvoices: "لا توجد فواتير في الوقت الحالي",
        noQuots: "لا توجد عروض في الوقت الحالي",
        invoice: "فاتورة",
        quot: "عرض سعر",
        card: {
            emmiter: "المرسل",
            targer: "المفوتر",
            totalAmount: "المبلغ الإجمالي",
            created: "تم الإنشاء في",
            edited: "تم التعديل في",
            isPayer: "مدفوعة",
            isNotPayed: "غير مدفوعة",
            invFor: "فاتورة لـ",
            detailButt: "تفاصيل الفاتورة",
            type: {
                "1": "شراء الموارد",
                "2": "مشروع",
                "3": "اشتراك",
            },
        },
        detail: {
            invoiceNum: "رقم",
            designation: "التعيين",
            price: "السعر",
            discount: "الخصم (%)",
            totalPrice: "الإجمالي",
            qte: "الكمية",
            grossTotal: "الإجمالي قبل الضريبة",
            generatedFooter: "فاتورة تم إنشاؤها تلقائيًا من قبل منصة سهلة ومهلة ™",
        },
    },
};
